version: '3'

services:
  server:
    image: registry.gitlab.com/matthew-beckett/netxms-dockerfiles/server:3-8-314
    ports:
    - "4700:4700"
    - "4701:4701"

  webui:
    image: registry.gitlab.com/matthew-beckett/netxms-dockerfiles/webui:3-8-314
    ports:
    - "8080:8080"
    environment:
      GMAIL_USER: "USER@gmail.com"
      GMAIL_PASSWORD: "PASSWORD"

  # webuirest:
  #   image: registry.gitlab.com/matthew-beckett/netxms-dockerfiles/webuirest:3-8-314
  #   ports:
  #   - "8080:8080"
  #   environment:
  #   - "NETXMS_SERVER=server"
  #   - "NETXMS_PORT=4701"

  agent:
    image: registry.gitlab.com/matthew-beckett/netxms-dockerfiles/nxagent:3-8-314
    environment:
      NETXMSD_UNLOCK_ON_STARTUP: 1
      NETXMSD_UPGRADE_ON_STARTUP: 1
      NETXMSD_DEBUG_LEVEL: 0
      NETXMSD_CONFIG: ""
      NETXMSD_UPGRADE_PARAMS: ""
    command: ["/wait-for", "netxms-agent:4700", "--", "./docker-entrypoint.sh"]
    
  netxms-webui:
    image: frostasm/netxms-webui:latest
    restart: unless-stopped
    ports:
      - "8080:8080" # http://server:8080/nxmc/nxmc
    environment:
      NETXMS_SERVER: "netxms-server"
    depends_on:
      - netxms-server
